# Generated by Django 3.2.7 on 2021-10-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(default='Без рубрики', help_text='Выберите рубрику из выпадающего списка', null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(help_text='Введите название товара (макс. симв. 50)', max_length=50, verbose_name='Товар'),
        ),
    ]
