# Generated by Django 3.2.7 on 2021-10-17 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20211017_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(default='Без рубрики', help_text='Выберите рубрику из выпадающего списка', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='bboard.rubric', verbose_name='Рубрика'),
        ),
    ]
