# Generated by Django 3.2.7 on 2021-10-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_bb_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['id'], 'verbose_name': 'рубрика', 'verbose_name_plural': 'рубрики'},
        ),
    ]
