# Generated by Django 3.2.7 on 2021-10-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_bb_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(help_text='Введите название товара (макс. симв. 255)', max_length=255, verbose_name='Товар'),
        ),
    ]
